### ISSUE TITLE
Encoder does not encode empty maps correctly

### ISSUE THREAD

**Issue by rweics** [linkedin/goavro#37]
When attempting to encode an empty map field(`map[string]interface{}{}`) whose schema is `{"type": ["null", {"type": "map", "values": "double"}]}`, it did not return any error. However, when trying to decode the binary produced by the encoder, it failed to decode and returned following error:
```
cannot decode record (Rec): 
	cannot decode record (NestedRec): 
		cannot encode union (union): 
			index must be between 0 and 1; read index: -59
```
Decoding the same binary using Java version of Apache Avro decoder, I got the following Exception:
```
java.lang.ArrayIndexOutOfBoundsException: -59
	at org.apache.avro.io.parsing.Symbol$Alternative.getSymbol(Symbol.java:402)
	at org.apache.avro.io.ResolvingDecoder.doAction(ResolvingDecoder.java:290)
	at org.apache.avro.io.parsing.Parser.advance(Parser.java:88)
	at org.apache.avro.io.ResolvingDecoder.readIndex(ResolvingDecoder.java:267)
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:155)
	at org.apache.avro.generic.GenericDatumReader.readField(GenericDatumReader.java:193)
	at org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:183)
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:151)
	at org.apache.avro.generic.GenericDatumReader.readField(GenericDatumReader.java:193)
	at org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:183)
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:151)
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:142)
```

**Comment by karrick** [comment]
Great trouble-shooting, and I appreciate the decoder breakdown from both goavro and the Apache Avro decoder. Looking into this issue...

**Comment by karrick** [comment]
awesome find
